CREATE TABLE IF NOT EXISTS `Drivers` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `firstName` VARCHAR(255) NOT NULL DEFAULT '',
    `lastName` VARCHAR(255) NOT NULL DEFAULT '',
    `birthday` DATE NOT NULL DEFAULT CURRENT_DATE,
    `code` VARCHAR(3) NOT NULL DEFAULT '',
    `number` TINYINT NOT NULL DEFAULT 0,
    `nationality` VARCHAR(255) NOT NULL DEFAULT '',
    `api_id` VARCHAR(36) NOT NULL DEFAULT 'Custom Driver',
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);