CREATE TABLE IF NOT EXISTS `GrandsPrix` {
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `officialName` VARCHAR(100) NOT NULL,
    `round` TINYINT NOT NULL,
    `date` DATETIME NOT NULL,
    `circuit` VARCHAR(100) NOT NULL
    `poleman` VARCHAR(20) NOT NULL,
    `winner` VARCHAR(20) NOT NULL,
    `secondPlace` VARCHAR(20) NOT NULL,
    `thirdPlace` VARCHAR(20) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
}